apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-db-pv-nfs
  labels:
    app: nextcloud-db-pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nextcloud/db
    server: host.docker.internal
    readOnly: false