apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-pvc-nfs
  namespace: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      app: nextcloud-db-pv-nfs