apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-secret
  namespace: nextcloud
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MlF2Mml4S0lRVjBrMHdDUVcwWHFKY3RwaWJqcVo3Yk0xYUM0NVIyV3NFbz0=
  MYSQL_USER: bmV4dGNsb3Vk
  MYSQL_PASSWORD: Syt1T2NLclpSTFF1TGpGTDBCL3RqNng0Q0pvWDUvL1VHd1ZWT0ZDeHpXMD0=