apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: nextcloud
spec:
  ports:
  - name: mariadb
    port: 3306
  selector:
    pod-label: nextcloud-db-pod # must match with the label of NFS pod